### ISSUE TITLE
20 - scoreboard - intro to javascript

### ISSUE THREAD

**Issue by alexalewis** [alexalewis/assignments#25]
# Score Board

For this assignment, you are creating a simple interactive scoreboard for your favorite sport.

## Requirements

- Refer to this mockup to design your page:

![](https://raw.githubusercontent.com/suncoast-devs/handbook/master/curriculum/fundamentals/modules/javascript/_old/assignments/assets/scoreboard.png)

- Use the HTML and CSS [here](https://gist.github.com/mdewey/d331c0a449b8e53b4adc472ec0e5a1e8) to jump-start your project.
- A user should be able to update a score and the teams playing.

### Part 1:

- [x] Create a new project using the `beta` stack and implement the design using the given HTML & CSS.
- [x] Assign click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard-coded" value.
- [x] Deploy your site.

### Part 2:

- [x] Add an `if` statement to stop each team's score from going below 0.
- [x] Add an `if` statement to stop each team's score from going above 21
- [x] When a team gets 21 points, disable the buttons and display a message to the user of who won
- [x] Add a `reset` button that resets the scoreboard back to each team having 0 points and re-enables the buttons

### Adventure Mode

- [ ] Add more CSS to the winning teams score to indicate who won.
- [ ] Implement a Quarter/Period Tracker that would be appropriate for the sport.
- [ ] Add some styling to make it more presentable. Have fun with it.
- [ ] Make the layout responsive.

### Epic Mode

- [ ] Add a Timer that counts down automatically and updates the period/quarter appropriately.
- [ ] Save/load the information to local storage.
- [ ] Add anything else that your sport would have on its scoreboard (e.g., fouls, sacks, shots on goal).
- [ ] Improve the UX to help to make scorekeeping by your sport easier.

**Comment by alexalewis** [comment]
https://github.com/alexalewis/my-score-board
